// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhvssfszcfrgjpyuvfyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodnNzZnN6Y2ZyZ2pweXV2ZnloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODUzNzQsImV4cCI6MjA2NTU2MTM3NH0.S6c8aarIWpbILEYD6BmdsBbiPSFjuFezglLfRzIhJ-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);